### PR TITLE
modify: Notice: S3 - Changes to Defaults (Block Public Access and ACL's)

### PR DESCRIPTION
**Pull request by Rahu2000**
Recently I tried to deploy an example resource using Terraform, and received the error:

Error: error creating S3 bucket ACL for bucket-name: AccessControlListNotSupported: The bucket does not allow ACLs │ status code: 400

so I tried to fix it

reference:
https://stackoverflow.com/questions/76049290/error-accesscontrollistnotsupported-when-trying-to-create-a-bucket-acl-in-aws

### CODE REVIEW

**Comment by leogr** [comment]
/ok-to-test

cc @LucaGuerra

**Comment by leogr** [comment]
cc @maxgio92

**Comment by maxgio92** [comment]
Hi @Rahu2000, does this new resource need a bump of the AWS Terraform provider?

**Comment by maxgio92** [comment]
/lgtm

This is the requirement right now for the AWS provider:
">= 4.0.0"

**Comment by Rahu2000** [comment]
Hi. 
@maxgio92 

Does not need.

-----Original Message-----

**Comment by maratsal** [comment]
Can you please use my PR https://github.com/falcosecurity/falco-aws-terraform/pull/6 instead of this one?

Since April 2023 All new S3 buckets are created with disabled public access - https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-s3-automatically-enable-block-public-access-disable-access-control-lists-buckets-april-2023/

and we just needed to make sure bucket ownership control is set to BucketOwnerEnforced

this was tested and works fine.

**Comment by maxgio92** [comment]
Hi @maratsal, thank you for your point.
Would you make a suggestion to this PR so that we might integrate it?

**Comment by maratsal** [comment]
Hi @maxgio92 

you can find my suggestion in the PR I referred to. Please feel free to use details from there and close PR that I have created.

**Comment by mstemm** [comment]
As suggested earlier in the comment thread, using the changes in the other PR https://github.com/falcosecurity/falco-aws-terraform/pull/6 instead

**Pull request closed without merging**
